#!/usr/bin/env bash
# gen-globals.sh — regenerate web/js/.globals.json from current source.
#
# The globals list for ESLint is AUTO-GENERATED, never hand-maintained: a hand
# list rots the instant the refactor moves a global. We grep every top-level
# (column-0) definition across web/js/*.js — function / async function /
# const NAME / let NAME / var NAME / class NAME — and emit them as ESLint
# "writable" globals plus a fixed set of browser/library/runtime globals.
#
# Why this catches the real failure mode: because the list is generated FROM the
# defining files, a function that's CALLED but DEFINED NOWHERE (a split dropped
# it, or a typo'd rename) is absent from .globals.json -> no-undef fires at the
# call site. That is exactly the "moved function lost its global" signal.
set -eu
cd "$(dirname "$0")"

OUT=.globals.json

# Source set = the browser app files only. The gate's OWN tooling (eslint.config,
# playwright.config(s), smoke.spec, the Node-only brainy_* test files + helper)
# is Node, not browser globals — exclude it from both globals-harvest and the
# net-globals count, or it pollutes the invariant.
SRC=$(ls *.js | grep -vE '^(eslint\.config|playwright\.config|playwright\.brainy\.config|smoke\.spec|brainy_helpers|brainy_[a-z0-9]+\.spec)\.js$' | tr '\n' ' ')

# --- 1. Project globals: every column-0 definition across web/js/*.js ---------
# Matches:  function NAME   async function NAME   const NAME   let NAME
#           var NAME   class NAME   (NAME = first identifier after the keyword)
# Two definition forms:
#   (a) column-0 declarations:  function/async function/const/let/var/class NAME
#   (b) window.NAME = ...        (some tools register handlers as window props)
decl_globals=$(
  grep -hoE '^(async[[:space:]]+)?(function|const|let|var|class)[[:space:]]+[A-Za-z_$][A-Za-z0-9_$]*' $SRC \
    | sed -E 's/^(async[[:space:]]+)?(function|const|let|var|class)[[:space:]]+//'
)
window_globals=$(
  grep -hoE '^window\.[A-Za-z_$][A-Za-z0-9_$]*[[:space:]]*=' $SRC \
    | sed -E 's/^window\.([A-Za-z_$][A-Za-z0-9_$]*).*/\1/'
)
project_globals=$(printf '%s\n%s\n' "$decl_globals" "$window_globals" | sort -u)

# --- 2. Ambient globals the source legitimately reads (not defined in web/js) --
# Browser DOM/runtime + the two CDN libs loaded before our scripts (marked, hljs)
# + Electron preload bridge. These are READ-only from our perspective.
ambient=$(cat <<'EOF'
window
document
console
navigator
location
history
localStorage
sessionStorage
fetch
FormData
Headers
Request
Response
URL
URLSearchParams
Blob
File
FileReader
WebSocket
EventSource
AbortController
setTimeout
clearTimeout
setInterval
clearInterval
requestAnimationFrame
cancelAnimationFrame
queueMicrotask
alert
confirm
prompt
atob
btoa
crypto
performance
Image
Audio
MediaRecorder
Notification
CustomEvent
Event
MutationObserver
ResizeObserver
IntersectionObserver
DOMParser
TextEncoder
TextDecoder
AbortSignal
ClipboardItem
event
structuredClone
getComputedStyle
matchMedia
HTMLElement
Node
NodeList
marked
hljs
CodeMirror
mermaid
electronAPI
EOF
)

# --- 3. Emit JSON: {"globals": {"NAME":"writable", ...}} ----------------------
{
  printf '{\n  "_comment": "AUTO-GENERATED by gen-globals.sh — do not edit. Regenerated as step 1 of js_gate.sh.",\n'
  printf '  "globals": {\n'
  first=1
  emit() {
    while IFS= read -r name; do
      [ -z "$name" ] && continue
      if [ $first -eq 1 ]; then first=0; else printf ',\n'; fi
      printf '    "%s": "%s"' "$name" "$2"
    done <<< "$1"
  }
  emit "$project_globals" "writable"
  emit "$ambient" "readonly"
  printf '\n  }\n}\n'
} > "$OUT"

count=$(grep -c '"writable"' "$OUT" || true)
echo "gen-globals: wrote $OUT ($count project globals)"
